### ISSUE TITLE
free plan deprecated

### ISSUE THREAD

**Issue by gigabit-eth** [alb2001/dextools-python#2]
The free plan has been deprecated and the lowest tier offered is "trial". 
The issue occurs on line 43:
```
plans = ["free", "standard", "advanced", "pro"]
```

**Comment by alb2001** [comment]
Hi, will work on it!

**Comment by alb2001** [comment]
Hi

I will work on it. I contacted the Dextools team to see what the new endpoints are.

Thanks
________________________________
De: lloyd ***@***.***>
Enviado: lunes, 12 de febrero de 2024 19:24
Para: alb2001/dextools-python ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [alb2001/dextools-python] free plan deprecated (Issue #2)


The free plan has been deprecated and the lowest tier offered is "trial".
The issue occurs on line 43:

plans = ["free", "standard", "advanced", "pro"]

**Comment by alb2001** [comment]
Hi

I updated the package on PyPi

Please try with the new one and let me know please.

Thank you.

**Comment by gigabit-eth** [comment]
Hi, 

Everything works now! 

Thank you very much!
