### ISSUE TITLE
There is no way to sort according to creation time and give a from and to timestamps

### ISSUE THREAD

**Issue by shanto12** [alb2001/dextools-python#3]

**Comment by alb2001** [comment]
Hi.

I developed some automatic testing and they seemed to work at the time.

Can you please provide a few code examples?

Thank you.

**Comment by shanto12** [comment]
or even better can you please provide your code sample where you used it in solana. Anyways my code sample as below.

curl -X GET "https://public-api.dextools.io/trial/v2/token/solana?sort=creationTime&order=desc&from=2024-02-01T00%3A00%3A00.000Z&to=2024-02-20T00%3A00%3A00.000Z" \
 -H "accept: application/json"\
 -H "x-api-key: ***********" \

response below.

{
  "statusCode": 200,
  "data": {
    "page": 0,
    "pageSize": 20,
    "totalPages": 0,
    "tokens": []
  }
}

Also, would you like to work together? I am creating a bot for arbitrage.. We can collaborate if thats fine with you.

**Comment by alb2001** [comment]
Hi

I see you're not using my sdk. You are sending a request using curl. If those results are not coming as expected and sort by "creationTime" is not working, then you should contact Dextools support instead as it might be an issue on their end.

**Comment by alb2001** [comment]
Closed due to inactivity
