### ISSUE TITLE
Solana tokens seem not to be able to get sorted by creationTime or creationBlock

### ISSUE THREAD

**Issue by pantlinardatos** [alb2001/dextools-python#4]
Specifically for Solana it seems that the API can not return creationTime or creationBlock

**Comment by alb2001** [comment]
Hi

Actually someone has reported a similar issue #3 
Can you please paste a code example here? You can use log level as debug and the log will print the url that is being set.

**Comment by pantlinardatos** [comment]
I sent a mail also to the official API support and they replied to me:

"Sorting by creationTime or creationBlock is not possible at this time, we're fixing an issue with the token creation times on Solana.
I'll come back to you when it's fixed."

So it seems that it is not an SDK problem

**Comment by alb2001** [comment]
Just checked, its not an issue with the SDK
